### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-aapb-annotations#7]
It might be nice to have the upload script (which is not in this repository) use a special branch to commit to, probably called `uploads`.

**Comment by marcverhagen** [comment]
Maybe, but for now we will just use the main branch for file/data uploads and the develop branch for code changes. We may change this later.

**Comment by keighrim** [comment]
Changes described in https://github.com/clamsproject/clams-aapb-annotations/issues/2#issuecomment-1180994334 will eliminate the necessity of keeping project-specific branches.

**Comment by keighrim** [comment]
No longer relevant, hence won't fix.
